kind = "mobile"
previewPath = "/"
title = "AkinAI"
version = "1.0.0"
id = "artifacts/akin-ai"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18157

[services.development]
run = "pnpm --filter @workspace/akin-ai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/akin-ai", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/akin-ai", "run", "serve" ]

[services.env]
PORT = "18157"
BASE_PATH = "/"
