const SCHOLARSHIPS = [
  {
    id: "mastercard-foundation",
    title: "Mastercard Foundation Scholars Program",
    organization: "Mastercard Foundation",
    location: "Africa, Americas, Lebanon",
    level: "Undergraduate / Postgraduate",
    deadline: "Rolling",
    amount: "Full tuition + stipend",
    url: "https://www.scholarshiptab.com/scholarships/africa/mastercard-foundation",
    tags: ["Africa", "Full-ride", "Leadership"],
  },
  {
    id: "chevening",
    title: "Chevening Scholarships",
    organization: "UK Government",
    location: "United Kingdom",
    level: "Master's",
    deadline: "November",
    amount: "Full tuition + living",
    url: "https://www.scholarshiptab.com/scholarships/united-kingdom/chevening",
    tags: ["UK", "Master's", "Fully-funded"],
  },
  {
    id: "daad",
    title: "DAAD Scholarships for Developing Countries",
    organization: "German Academic Exchange Service",
    location: "Germany",
    level: "Master's / PhD",
    deadline: "Varies",
    amount: "€861–€1,200 / month",
    url: "https://www.scholarshiptab.com/scholarships/germany/daad",
    tags: ["Germany", "Research", "Developing"],
  },
  {
    id: "commonwealth",
    title: "Commonwealth Scholarships",
    organization: "Commonwealth Scholarship Commission",
    location: "United Kingdom",
    level: "Master's / PhD",
    deadline: "October",
    amount: "Full tuition + stipend",
    url: "https://www.scholarshiptab.com/scholarships/united-kingdom/commonwealth",
    tags: ["Commonwealth", "Fully-funded"],
  },
  {
    id: "fulbright",
    title: "Fulbright Foreign Student Program",
    organization: "U.S. Department of State",
    location: "United States",
    level: "Master's / PhD",
    deadline: "Varies by country",
    amount: "Full tuition + travel",
    url: "https://www.scholarshiptab.com/scholarships/united-states/fulbright",
    tags: ["USA", "Research", "Fully-funded"],
  },
  {
    id: "mext",
    title: "MEXT Japanese Government Scholarship",
    organization: "Government of Japan",
    location: "Japan",
    level: "Undergraduate / Master's / PhD",
    deadline: "April / May",
    amount: "Full tuition + monthly stipend",
    url: "https://www.scholarshiptab.com/scholarships/japan/mext",
    tags: ["Japan", "Government", "Fully-funded"],
  },
  {
    id: "african-union",
    title: "African Union Scholarship Programme",
    organization: "African Union",
    location: "Pan-African",
    level: "Undergraduate / Postgraduate",
    deadline: "Varies",
    amount: "Tuition + stipend",
    url: "https://www.scholarshiptab.com/scholarships/africa",
    tags: ["Africa", "Pan-African"],
  },
  {
    id: "wur-liberia",
    title: "Scholarships for Liberian Students",
    organization: "Various",
    location: "Liberia / International",
    level: "All levels",
    deadline: "Varies",
    amount: "Varies",
    url: "https://www.scholarshiptab.com/scholarships/liberia",
    tags: ["Liberia", "West Africa"],
  },
  {
    id: "google-generation",
    title: "Generation Google Scholarship",
    organization: "Google",
    location: "Global",
    level: "Undergraduate / Master's",
    deadline: "December",
    amount: "$1,000 – $10,000",
    url: "https://www.scholarshiptab.com/scholarships/computer-science",
    tags: ["Tech", "Women in STEM", "Computer Science"],
  },
  {
    id: "rhodes",
    title: "Rhodes Scholarships",
    organization: "Rhodes Trust",
    location: "Oxford, United Kingdom",
    level: "Master's / PhD",
    deadline: "August",
    amount: "Full ride + stipend",
    url: "https://www.scholarshiptab.com/scholarships/united-kingdom/rhodes",
    tags: ["Oxford", "Prestigious", "Fully-funded"],
  },
  {
    id: "schwarzman",
    title: "Schwarzman Scholars Program",
    organization: "Tsinghua University",
    location: "Beijing, China",
    level: "Master's",
    deadline: "September",
    amount: "Full tuition + travel + stipend",
    url: "https://www.scholarshiptab.com/scholarships/china/schwarzman",
    tags: ["China", "Leadership", "Fully-funded"],
  },
  {
    id: "knight-hennessy",
    title: "Knight-Hennessy Scholars",
    organization: "Stanford University",
    location: "United States",
    level: "Graduate",
    deadline: "October",
    amount: "Full funding",
    url: "https://www.scholarshiptab.com/scholarships/united-states/stanford",
    tags: ["Stanford", "USA", "Leadership"],
  },
];

export default function handler(_req: any, res: any) {
  res.status(200).json({
    source: "ScholarshipTab",
    sourceUrl: "https://www.scholarshiptab.com/",
    items: SCHOLARSHIPS,
  });
}
